version: '3.8'

services:
  nginx:
    restart: unless-stopped
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

  api:
    build:
      context: '../backend'
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000
